// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence.EF;

#nullable disable

namespace Persistence.EF.Migrations
{
    [DbContext(typeof(TaskManagerContext))]
    partial class TaskManagerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Domain.Core.TaskModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CompleteStatus")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("ExpirationDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tasks");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ed4bf9d1-a7c4-4f89-8d0d-4fac1bf8f294"),
                            CompleteStatus = 0,
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 4, 25, 23, 34, 8, 30, DateTimeKind.Unspecified).AddTicks(1859), new TimeSpan(0, 2, 0, 0, 0)),
                            Description = "Zrobic zakupy w sklepie, koszt bulek 0.40gr",
                            ExpirationDate = new DateTimeOffset(new DateTime(2022, 4, 26, 23, 34, 8, 30, DateTimeKind.Unspecified).AddTicks(1811), new TimeSpan(0, 2, 0, 0, 0)),
                            Title = "Kupic bulki"
                        },
                        new
                        {
                            Id = new Guid("ef20f70e-4b78-45eb-9404-de3da9ff16dc"),
                            CompleteStatus = 0,
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 4, 25, 23, 34, 8, 30, DateTimeKind.Unspecified).AddTicks(1898), new TimeSpan(0, 2, 0, 0, 0)),
                            ExpirationDate = new DateTimeOffset(new DateTime(2022, 4, 27, 23, 34, 8, 30, DateTimeKind.Unspecified).AddTicks(1895), new TimeSpan(0, 2, 0, 0, 0)),
                            Title = "Natankowac samochod"
                        },
                        new
                        {
                            Id = new Guid("e74dc990-5488-4b39-aecc-28c1eecb011f"),
                            CompleteStatus = 0,
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 4, 25, 23, 34, 8, 30, DateTimeKind.Unspecified).AddTicks(1904), new TimeSpan(0, 2, 0, 0, 0)),
                            ExpirationDate = new DateTimeOffset(new DateTime(2022, 5, 3, 23, 34, 8, 30, DateTimeKind.Unspecified).AddTicks(1901), new TimeSpan(0, 2, 0, 0, 0)),
                            Title = "Napic sie kawy"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
