// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence.EF;

#nullable disable

namespace Persistence.EF.Migrations
{
    [DbContext(typeof(TaskManagerContext))]
    partial class TaskManagerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Domain.Core.TaskModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CompleteStatus")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("ExpirationDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tasks");

                    b.HasData(
                        new
                        {
                            Id = new Guid("26b233e9-cbd9-4e0f-ad75-7993e5d7399b"),
                            CompleteStatus = 0,
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 4, 24, 21, 46, 35, 605, DateTimeKind.Unspecified).AddTicks(5222), new TimeSpan(0, 2, 0, 0, 0)),
                            Description = "Zrobic zakupy w sklepie, koszt bulek 0.40gr",
                            ExpirationDate = new DateTimeOffset(new DateTime(2022, 4, 25, 21, 46, 35, 605, DateTimeKind.Unspecified).AddTicks(5175), new TimeSpan(0, 2, 0, 0, 0)),
                            Title = "Kupic bulki"
                        },
                        new
                        {
                            Id = new Guid("04695079-2d60-4c94-a15a-12ad10fb08ec"),
                            CompleteStatus = 0,
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 4, 24, 21, 46, 35, 605, DateTimeKind.Unspecified).AddTicks(5255), new TimeSpan(0, 2, 0, 0, 0)),
                            ExpirationDate = new DateTimeOffset(new DateTime(2022, 4, 26, 21, 46, 35, 605, DateTimeKind.Unspecified).AddTicks(5252), new TimeSpan(0, 2, 0, 0, 0)),
                            Title = "Natankowac samochod"
                        },
                        new
                        {
                            Id = new Guid("aeec3b85-7623-4c63-b0fc-f5efcb25567c"),
                            CompleteStatus = 0,
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 4, 24, 21, 46, 35, 605, DateTimeKind.Unspecified).AddTicks(5260), new TimeSpan(0, 2, 0, 0, 0)),
                            ExpirationDate = new DateTimeOffset(new DateTime(2022, 5, 2, 21, 46, 35, 605, DateTimeKind.Unspecified).AddTicks(5258), new TimeSpan(0, 2, 0, 0, 0)),
                            Title = "Napic sie kawy"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
